# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/bionic64"
NODE_COUNT = 1
  
Vagrant.configure("2") do |config|   
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |config|
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "11.11.11.11"
    config.vm.box = BOX_IMAGE
    config.vm.provision :shell, path: "setup-webserver.sh"
    end
  end
end
